name: FetchStockData

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Delete dataset folder, download norn-data into dataset folder
      run: |-
        rm -rf ./dataset
        git clone --single-branch --branch gh-pages git@github.com:zmcx16/Norn-StockScreener.git
        mv ./Norn-StockScreener/norn-data ./dataset
    - name: Copy master folder
      run: |-
        rsync -Rr ./ ./master/
    - name: Checkout data branch
      run: |-
        git checkout data
    - name: Install Python dependencies
      run: |
        python -m pip install -r ./master/requirements.txt
    # - name: Run forecast
    #  run: |-
    #    python ./master/fetch_stock_data.py
    - name: Copy forecast_output
      run: |-
        cp -r ./master/forecast_output ./
    - name: Delete master folder
      run: |-
        rm -rf ./master
    - name: Add forecast_output and push it
      run: |-
        git config --global user.name "zmcx16-bot"
        git reset --soft HEAD~1
        git add ./forecast_output/\* && git commit -m "updated forecast_output"
        git push -f
